### Link de Material Complementario

https://1drv.ms/u/s!Anh5cvrOJtUTk942w5OEyvQLHGSNeA?e=8kNbX4

# MODULO 3 - Biblioteca Numpy 3

## 3.1. Missing Values
¿Qué sucede con las funciones y métodos cuando el array  tiene missing values?
Están diseñadas para propagar el valor al resultado final.      
Para ignorar los missing values se deben usar las funciones  **nansum**, **nanprod**, **nanmean**, **nanstd**, **nanvar**, **nanmin**,  **nanmax**, etc. Estas funciones no tienen métodos equivalentes.

In [2]:
import numpy as np

In [3]:
a= np.array([1, 1, np.nan, 1])
a

array([ 1.,  1., nan,  1.])

In [4]:
a.mean(), np.max(a), a.sum()

(nan, nan, nan)

In [5]:
np.nanmean(a), np.nanmax(a), np.nansum(a)

(1.0, 1.0, 3.0)

# MODULO 3 - Biblioteca Numpy 4

## 4.1.- Álgebra Lineal
Hemos visto hay numerosas operaciones que se  pueden hacer con arrays. Algunas son elemento a  elemento, otras son sobre el conjunto de los datos, o  en alguno de los ejes.
Además de todo eso, Numpy implementa muchas  operaciones de álgebra lineal, como producto escalar  entre vectores, producto matricial, cálculo de  determinante, matriz inversa, etc.

### 4.1.1.- Producto Escalar
Recordemos qué es el producto escalar de  dos vectores. Si tenemos los vectores v y w el  producto escalar es:
![imagen](producto_escalar.png)

In [6]:
v = np.array([5, 3, 2, 6])
w = np.array([1, 2, 0, 8])

print(v.dot(w))
print (v @ w)

59
59


### 4.1.2.- Producto Matricial
El método **dot** y su correspondiente operador **@**  se pueden usar también para efectuar productos  matriciales, en donde cada elemento de la nueva  matriz es el producto escalar de una fila de la  primer matriz y una columna de la segunda. La  cantidad de columnas de la primer matriz debe  ser igual a la cantidad de filas de la segunda.
![imagen](matricial.png)

In [8]:
A = np.array([[2, 5, 3], [7, 1, 4]])
print(A)
print('________________')
B = np.array([[3, 2], [9, 6],[5, 8]])
print(B)

[[2 5 3]
 [7 1 4]]
________________
[[3 2]
 [9 6]
 [5 8]]


In [9]:
A.dot(B)

array([[66, 58],
       [50, 52]])

### 4.1.3.-  Matriz Transpuesta
Cuando se trabaja con matrices es muy usual  tener que obtener la ***matriz transpuesta***. Para  obtenerla podemos usar el método transpose  o el atributo T.

In [11]:
A = np.array([[2, 5, 3], [7, 1, 4]])
print(A)


[[2 5 3]
 [7 1 4]]


In [12]:
A.T

array([[2, 7],
       [5, 1],
       [3, 4]])

### 4.1.4.-  Determinate de una Matriz 
Numpy tiene un módulo dedicado a álgebra  lineal: el módulo ***linalg***, donde se implementan  muchas funciones de álgebra lineal. Una de ellas  es det, que calcula el determinante de una  matriz cuadrada.

In [13]:
M = np.array([[0, 7, 0], [0, 2, 6], [4, 3, 2]])
print(M)

[[0 7 0]
 [0 2 6]
 [4 3 2]]


In [14]:
np.linalg.det(M)

167.99999999999997

### 4.1.5.-  Matriz Inversa
También podemos encontrar la inversa de una matriz  cuadrada de determinante no nulo con la función **inv**.

In [15]:
np.linalg.inv(M)

array([[-0.08333333, -0.08333333,  0.25      ],
       [ 0.14285714,  0.        ,  0.        ],
       [-0.04761905,  0.16666667,  0.        ]])

# Modulo 4.- Pandas 1

## 1.1. Que es Pandas
Pandas es un módulo muy popular para manipulación  y análisis de datos. Está hecho sobre Numpy y provee  estructuras de datos diseñadas para trabajar con datos estructurados (tablas). A diferencia de un array de numpy,  pandas permite trabajar con distintos tipos de datos  para cada columna asemejándose más a lo que se usa  en bases de datos relacionales.
Tiene dos estructuras de datos: **la serie** y **el  dataframe**.

El primero es un arreglo unidimensional  etiquetado y con un tipo de dato determinado.

El  dataframe es una estructura bidimensional similar a  una tabla que admite etiquetas para filas y columnas.  Cada columna de un dataframe es una serie.
![immagen](pandas.png)

## 1.2. Series
La **serie** es una estructura de datos unidimensional en donde  cada dato tiene además una etiqueta. 
Es una estructura  mutable a la que no sólo se le puede cambiar sus elementos, si no que además se le pueden agregar y quitar elementos.

Se refiere a las etiquetas colectivamente como **index**, y las  etiquetas no tienen por qué ser únicas.      
Estas etiquetas  añaden funcionalidad para manipular los datos. Para crear  una serie se usa el constructor **pd.Series()** que es capaz de  convertir a serie distintas estructuras como listas,  diccionarios, arrays, etc.      
También tiene un atributo nombre,  que es el que se utiliza como etiqueta de la columna cuando  forma parte de un dataframe.

In [16]:
import pandas as pd
import numpy as np

In [17]:
pd.Series([5, 7, 2])

0    5
1    7
2    2
dtype: int64

In [18]:
pd.Series([5, 7, 2], index = ['a', 'b', 'c'], dtype = 'int8', name = 'numeros')

a    5
b    7
c    2
Name: numeros, dtype: int8

In [19]:
pd.Series({'Martin': 8, 'Juan': 9, 'Lucia': 7}, name = 'notas')

Martin    8
Juan      9
Lucia     7
Name: notas, dtype: int64

## 1.3. Dataframe
El dataframe es la estructura más utilizada de pandas. Es  una estructura bidimensional tipo tabla con etiquetas para  filas y columnas, lo que da más flexibilidad a la hora de  manipular los datos.      
Cada columna puede tener su propio  tipo de dato.
Es mutable tanto en los datos como en su tamaño, por lo que  se pueden añadir o quitar filas y columnas.      
Cada columna es  una serie en donde todas las series tienen el mismo index.
Para crear  una serie se usa el constructor **pd.DataFrame()** que es capaz de  convertir a serie distintas estructuras como listas,  diccionarios, arrays.

In [20]:
# desde listas anidadas

pd.DataFrame([[0, 1, 2], [3, 3, 5], [6, 7, 8]])

0  1  2
0  0  1  2
1  3  3  5
2  6  7  8

In [21]:
# desde listas anidadas y definiendo index y columnas

pd.DataFrame([[0, 1, 2], [3, 3, 5], [6, 7, 8]], index = ['a', 'b', 'c'], columns = ['lunes', 'martes', 'miercoles'] )

lunes  martes  miercoles
a      0       1          2
b      3       3          5
c      6       7          8

In [22]:
# desde un array de numpy

array = np.random.randint(0, 50, (3,5))
array

array([[32, 14,  9,  3, 19],
       [47, 11, 46, 17, 48],
       [36, 10, 31, 31, 41]])

In [23]:
pd.DataFrame(array)

0   1   2   3   4
0  32  14   9   3  19
1  47  11  46  17  48
2  36  10  31  31  41

In [24]:
# desde un diccionario

pd.DataFrame({'Columna 1': [1, 2, 3], 'Columna 2': [4, 5, 6]}, index = ['A', 'B', 'C'])

Columna 1  Columna 2
A          1          4
B          2          5
C          3          6

## 1.4. Lectura de archivos con Pandas
Pandas tiene numerosas funciones para leer diferentes  formatos de archivos y construir dataframes a partir de ellos.    
Esto facilita enormemente la tarea de importar los datos.
Entre los formatos que se pueden leer podemos encontrar  csv, excel, json, html, sql, entre otros.
Los nombres de estas funciones empiezan con el prefijo  **read_**, por ejemplo, **pd.read_csv**, **pd.read_excel**, etc.    
Cada una de estas funciones tiene numerosos parámetros  para controlar cómo se realiza la lectura si es necesario.

Para practicar las funcionalidades que ofrece pandas vamos a  trabajar con un dataset muy conocido, el del Titanic.    
En el  material del Alumni se provee el archivo **“titanic.csv”**, que  vamos a abrir con la función **read_csv**.    
El primer parámetro  puede ser un string con la ruta absoluta o relativa al archivo.  Si el archivo se encuentra en el mismo directorio que la  jupyter notebook, se puede poner simplemente el nombre  del archivo. Además, se pueden pasar URLs de archivos csv.
La función va a crear un DataFrame a partir del archivo. En  general no hace falta especificar más parámetros pero si es  necesario se puede controlar cada detalle de cómo se realiza  la lectura del archivo.

In [27]:
data = pd.read_csv('titanic.csv')
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [28]:
#pd.set_option("max_colwidth", None)

#pd.set_option('display.max_rows', None)

Para mostrar todas las filas, establezca max_rows mayor que el número de filas del DataFrame. Para mostrar más de 10 filas cuando se trunca el DataFrame, establezca min_rows mayor que 10. Con más de 200 filas de datos, si max_rows es 200 y min_rows es 20, se mostrarán 10 desde la cabeza y 10 desde la cola. Con más de 200 filas de datos, si max_rows es 200 y min_rows es Ninguno, se mostrarán 100 desde la cabeza y 100 desde la cola.

## 1.5. Explorando el Dataframe

Se pueden visualizar filas del comienzo del dataframe con el  método **head**, y del final con el método **tail**. En ambos se  puede especificar la cantidad de filas a imprimir.    
El método  **info** imprime información sobre un DataFrame que incluye el  tipo de índice y los tipos de columna, los valores no nulos y el  uso de memoria.

También se puede ver los atributos dtype (tipo de dato de  cada columna), shape (dimensiones del dataframe),  size  (cantidad de elementos). Las etiquetas se pueden ver con los  atributos  index y columns, que además permiten  reasignarlos para modificar las etiquetas. El atributo values  devuelve una representación del dataframe como un array de  numpy.

In [29]:
data.tail(5)

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
